### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by Dhawal-1** [appwrite/sdk-for-python#68]
### 💭 Description

createEmailSession Function not on Python.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Dhawal-1 thanks for creating this issue! 🙏🏼 This is actually expected because the Python SDK is a server-side SDK and it's not designed to be called by an end user. People typically create a session client side, [generate a JWT token](https://appwrite.io/docs/client/account?sdk=web-default#accountCreateJWT), and then pass it to the Python server so that the server can make requests using that JWT token.

For more info, see https://appwrite.io/docs/authentication-server.

Since this is as designed, can this be closed?
